name: cmake

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  DEBIAN_FRONTEND: noninteractive
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  macos-11:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Set up dependencies
        run: |
          brew install cmake fluid-synth liblo libmagic libsndfile pkg-config
      - name: configure
        run: cmake -S cmake -B cmake
      - name: build
        run: make -C cmake -j $(sysctl -n hw.logicalcpu)

  ubuntu-20_04:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -yqq cmake libfluidsynth-dev liblo-dev libmagic-dev libsndfile1-dev libx11-dev pkg-config
      - name: configure
        run: cmake -S cmake -B cmake
      - name: build
        run: make -C cmake -j $(nproc)

  ubuntu-22_04:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -yqq cmake libfluidsynth-dev liblo-dev libmagic-dev libsndfile1-dev libx11-dev pkg-config
      - name: configure
        run: cmake -S cmake -B cmake
      - name: build
        run: make -C cmake -j $(nproc)
