name: ubuntu latest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install extra dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev liblo-dev libfluidsynth-dev libgl1-mesa-dev libgtk2.0-dev libgtk-3-dev libmagic-dev libpulse-dev libx11-dev pkg-config pyqt5-dev-tools qtbase5-dev
          sudo apt-get install mingw-w64 binutils-mingw-w64-x86-64 g++-mingw-w64-x86-64 wine-stable wine-stable-dev
      - name: make features
        run: make features
      - name: make
        run: make
